name: PALADIN CI
on:
  push:
    branches: ["**"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install requirements (if present)
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Pre-commit (optional)
        if: hashFiles('.pre-commit-config.yaml') != ''
        run: |
          pip install pre-commit
          pre-commit run --all-files || true

      - name: Build receipts
        run: |
          set -e
          if [ -f Makefile ] && grep -qE '(^|\n)ci:' Makefile; then
            make ci
          elif [ -f scripts/check_feedback.py ]; then
            mkdir -p artifacts
            python -m scripts.check_feedback --outdir artifacts
          else
            echo "No Makefile:ci or scripts/check_feedback.py found — creating placeholder summary."
            mkdir -p artifacts
            echo "## PALADIN CI\nNo entrypoint detected. Add a Makefile 'ci' target or scripts/check_feedback.py." > artifacts/summary.md
          fi

      - name: Job Summary
        if: always()
        run: |
          if [ -f artifacts/summary.md ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            cat artifacts/summary.md >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: paladin-receipts
          path: artifacts/*
